name: vandyscripts

channels:
  - defaults

dependencies:
  - python>=3.6
  - anaconda
  - ipython
  - numpy
  - pandas
  - ads
  - requests
  - lxml
  - html5lib
  - BeautifulSoup4
  - pip
  - pip:
    - arxiv
    # - xmlrpclib
