name: vandyscripts

dependencies:
  - python>=3.6
  - anaconda
  - ipython
  - numpy
  - pandas
  - ads
  - requests
  - pip
  - pip:
    - autoenv
    - lxml
    - html5lib
    - BeautifulSoup4
    - conda-autoenv
